services:
  pylauncher:
    build: .
    image: pylauncher:installer-1.18.1
    container_name: pylauncher
    volumes:
      - PyLauncherVD:/app/PyLauncher/home/cluster/global/
      - PyLauncherVC:/app/PyLauncher/config/controller/
      - PyLauncherLog:/app/PyLauncher/logs/
    restart: unless-stopped

volumes:
  PyLauncherVD:
    external: true
  PyLauncherVC:
    external: true
  PyLauncherLog:
    external: true