services:
  pylauncher:
    build: .
    image: pylauncher:installer-1.17
    container_name: pylauncher
    volumes:
      - PyLauncherVD:/app/PyLauncher/home/cluster/global/
      - pyLauncherVC:/app/PyLauncher/config/controller/
    restart: unless-stopped

volumes:
  PyLauncherVD:
    external: true
  PyLauncherVC:
    external: true